### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by FranklinOP-IND** [fusedevgithub/Colab-DDos-Panel#1]
![image](https://user-images.githubusercontent.com/64591314/151131112-31c9e9b5-aca8-43c2-8027-6ecebbcac75c.png)
to many time download but worked proxy error

**Comment by fusedevgithub** [comment]
These bugs are DDoS scripts
you can try changing script DDoS
maybe because DDoS scripts are not updated or proxy server is issues
Now I know the issues and I gonna update on soon.

**Comment by FranklinOP-IND** [comment]
Ok Gud 
MHDDoS New Scripts Update i will try to change
