### ISSUE TITLE
Add new scipt

### ISSUE THREAD

**Issue by Xoosz** [fusedevgithub/Colab-DDos-Panel#2]
add new mhddos update in colab pls

**Comment by fusedevgithub** [comment]
got it,

**Comment by fusedevgithub** [comment]
https://colab.research.google.com/github/fusedevgithub/Colab-DDos-Panel/blob/main/Colab_DDos_Panel.ipynb

**Comment by Xoosz** [comment]
Okay thanks bro

**Comment by fusedevgithub** [comment]
So i will closed this issues
I gonna update new tools in coming soon.
